# Site settings
name: Divjeet Singh Jas
title: Divjeet Singh Jas | Front End Software Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://singhdivjeet.github.io/portfolio-website-v2/
baseurl: ""
email: djas@ucdavis.edu
cover: https://singhdivjeet.github.io/portfolio-website-v2/img/og.png
logo: https://singhdivjeet.github.io/portfolio-website-v2/img/emojis/technologist.png
resume: https://singhdivjeet.github.io/portfolio-website-v2/resume.pdf
social:
  - title: email
    url: mailto:djas@ucdavis.edu
  - title: twitter
    url: https://twitter.com/singhdivjeet
  - title: instagram
    url: https://www.instagram.com/singhdivjeet/

  - title: github
    url: https://github.com/singhdivjeet
  - title: linkedin
    url: https://www.linkedin.com/in/divjeet-singh/

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
